##
##
##

nodes:
  - rank: 0 # rank of this node
    master: # this is the master node
      address: '127.0.0.1'
      port: '24900'
    devices:
      gpus: 3 # how many gpus to use
    # this is equivalent to
    # gpus:
    #   - 0
    #   - 1
    #   - 2
  - rank: 1
    devices:
      gpus: # you can also list which gpus you want to use
        - 0
        - 1
        - 3
        - 4
      cpus: 1 # you can only specify how many cpus to use
      # note that you can use both cpus and gpus in the same device
      # however this is not recommended
