##
##
##

seed: 3407

datasets:
  - name: 'ntu60-xview'
    dataset_path: 'data/ntu60-xview'
    generation_args: 
      ignored_file: 'data/ignore.txt'
      ntu60_path: 'data/nturgb+d_skeletons'
      num_frames: 64
    training_args:
      normalize: True
      change_probability: 0.15
      shuffle_probability: 0.15
      shuffle_length: 3
  - name: 'ntu60-xview'
    dataset_path: 'data/ntu60-xview'
    training_args:
      normalize: True
      change_probability: 0.15
      shuffle_probability: 0.15
      shuffle_length: 3
      actions: [0, 1]
      joints: [0, 1, 2, 3, 20, 4, 8]

models:
  - name: 'MS-STE'
    architecture: 'config/model.yaml'

tests:
  - batch_size: 64

trainings: 
  - model: 0
    dataset: 0
    #work_dir: ''
    #resume: ''
    classification_args:
      dataset: 0
      train_batch_size: 64
      eval_batch_size: 64
      accumulation_steps: 16
      num_epochs: 1
      save_interleave: 1
      optimizer: 0
      scheduler: 1
      label_smoothing: 0.1
    finetune_args:
      dataset: 1
      train_batch_size: 64
      eval_batch_size: 64
      accumulation_steps: 16
      num_epochs: 1
      save_interleave: 1
      optimizer: 0
      scheduler: 1
      label_smoothing: 0.1
      

optimizers: 
  - name: 'AdamW'
    args:
      lr: 0.001
  - name: 'SGD'
    args:
      lr: 0.1
      momentum: 0.9
      nesterov: False
      weight_decay: 0.0001

lr_schedulers: 
  - name: 'CosineLRScheduler'
    args:
      t_initial: 10
      t_mul: 2
  - name: 'OneCycleLR'
    step_after_batch: True
    args:
      max_lr: 0.001
      three_phase: True
