##
##
##

sublayer_dropout: 0.2
feature_dropout: 0.1
structure_dropout:
  start: 0.2
  end: 0.2
  warmup: 8
embeddings:
  temporal_channels: 64
  type_channels: 5
encoder:
  blocks:
    - channels: 64
      layers:
        - num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - cross_view: 'larger'
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
    - channels: 128
      layers:
        - num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - cross_view: 'larger'
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
    - channels: 256
      layers:
        - num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - cross_view: 'smaller'
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
decoder:
  blocks:
    - channels: 128
      layers:
        - num_heads: 8
          branches:
            - window: 3
              dilation: 1
    - channels: 96
      layers:
        - num_heads: 8
          branches:
            - window: 3
              dilation: 1
    - channels: 64
      layers:
        - num_heads: 8
          branches:
            - window: 3
              dilation: 1
        - num_heads: 8
          branches:
            - window: 5
              dilation: 1
              
