##
##
##

sublayer_dropout: 0.2
feature_dropout: 0.1
structure_dropout: 0.2
embeddings:
  temporal_channels: 64
  type_channels: 5
encoder:
  blocks:
    - channels: 64
      layers:
        - cross_view: false
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - cross_view: True
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - cross_view: false
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
    - channels: 96
      layers:
        - cross_view: false
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - cross_view: True
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - cross_view: false
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
    - channels: 128
      layers:
        - cross_view: false
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - cross_view: True
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
        - cross_view: false
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
            - window: 3
              dilation: 2
            - window: 3
              dilation: 3
            - window: 3
              dilation: 4
decoder:
  blocks:
    - channels: 128
      layers:
        - cross_view: False
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
    - channels: 96
      layers:
        - cross_view: False
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
    - channels: 64
      layers:
        - cross_view: False
          num_heads: 8
          branches:
            - window: 3
              dilation: 1
        - cross_view: False
          num_heads: 8
          branches:
            - window: 5
              dilation: 1
              
